### ISSUE TITLE
Weird seed bug on server but not in single player

### ISSUE THREAD

**Issue by Saereth** [TehNut-Mods/ResourcefulCrops#13]
So we added some custom seeds to the json file, they work perfectly in single player. Once you get onto the server however things go sideways. In this case we added gainite seeds and then removed the recipe and had them drop as loot instead. When players plant the gainite seeds they turn into copper plants visually bit give Gainite shards, but those shards craft into copper not gainite. its so weird 0.o.

You can view our configs here in case I've derped on them. 

https://github.com/breakinblocks/nutsandbolts/blob/develop/config/ResourcefulCrops/seeds/DefaultSeeds.json

**Comment by TehNut** [comment]
This was due to an issue with the Seed Caching. The server didn't generate one, but the client did. So the server is loading in a different order than the client. Have each of your clients delete their cache from `../saves/` and it _should_ fix itself. More of a bandage than a fix, but that's really all there is to do for now.

This problem will be solved once I figure out how to send the cache from the server to the client on connect. See #9

**Comment by Saereth** [comment]
That seems to have taken care of it, good luck on the cache transfer!
