### ISSUE TITLE
Agricraft and YOU

### ISSUE THREAD

**Issue by Fortist** [TehNut-Mods/ResourcefulCrops#26]
Well, Im trying to configure new crops and remove stupid ones from the default.
However, when changing the first three in most ways, I get one kind of crash.
I think removing "Vanilla" stuff causes the crash, as I did try and remove the Gunpowder seed as well.
When adding new crops, I get the same crash I think.
I assume it's an Agricraft thing.
http://pastebin.com/wT68zWsK

Probably gonna go post this aswell on the Agri Github

**Comment by TehNut** [comment]
Removing should have no effect on this. Try adding `"seedReq": {}` to your additional seeds. 

I didn't fully understand how JSON worked when I moved over to it, so a lot of my handling is archaic and [just plain stupid](https://github.com/TehNut/ResourcefulCrops/blob/1.7.10/src/main/java/tehnut/resourceful/crops/util/serialization/SeedCreator.java#L47).

**Comment by InfinityRaider** [comment]
You can let Gson write the file for you, I tend to do that, it works very well and haven't had any issues with it so far.

**Comment by InfinityRaider** [comment]
To get to the point, not sure if this is an issue in my code or in yours. Are there things null that shouldn't be null? Or did I miss a needed null check?

**Comment by TehNut** [comment]
> You can let Gson write the file for you, I tend to do that, it works very well and haven't had any issues with it so far.

Yeah I learned that a while after doing the JSON for this. I'll be rewriting it in the 1.8 version (sadly, that will require everybody to nuke their old configs).

> To get to the point, not sure if this is an issue in my code or in yours. Are there things null that shouldn't be null? Or did I miss a needed null check?

Looking into that right now. As mentioned above, adding `"seedReq": {}` should be a working ~~solution~~ bandaid for OP, as that's what all the default seeds use.

**Comment by TehNut** [comment]
I'm actually not sure why that would be returning null... If the `seedReq` JSON object doesn't exist, I just return a default one.

@Fortist Could I see your current seed JSON?

**Comment by Fortist** [comment]
http://pastebin.com/tAmzZ3CK

Like, I can get rid of Cobalt and Ardite. But if I try and get rid of "Inky" or even rename it, I get that crash.

**Comment by TehNut** [comment]
Ahhh, I see what's happening here. `SeedRegistry.getSeedList()` isn't the primary "registry" list. I set that later [here](https://github.com/TehNut/ResourcefulCrops/blob/1.7.10/src/main/java/tehnut/resourceful/crops/ResourcefulCrops.java#L106) for more efficient lookup. The _actual_ registry list is [here](https://github.com/TehNut/ResourcefulCrops/blob/1.7.10/src/main/java/tehnut/resourceful/crops/ResourcefulCrops.java#L61) (The cache). 

The cache is used to make sure there's no shifting of ID's when the world is reloaded with a modified seed list. (IE: Remove index 7, everything after that gets shifted left one)

Because of this, old ID spots are blacklisted from future use. When setting the Seed list, those blacklisted spots effectively become `null` as there is no data to put there.

I can't really think of a fix for this on my end as it's just how the cache works.

**Comment by Armagedon13** [comment]
Try to go in your Saves folder, and delete ResourcefulCropsCache.dat.

**Comment by TehNut** [comment]
Non-issue on modern MC
