### ISSUE TITLE
Pull Requests allowed?

### ISSUE THREAD

**Issue by ceiphas** [TehNut-Mods/ResourcefulCrops#37]
I read the reddit post here: [https://www.reddit.com/r/feedthebeast/comments/3czumb/resourcefulcrops_an_open_source_magical_crops/](url)

and now i don't know if i am alloed to clone your repository and add some functionality for you to do a pull request.

i added two things on my local machine, i can upload them to github, if it is allowed:

first i added a config value "extraSeedDefaultChance" (float from 0.0 to 1.0, default 0.1) so the seeds will propagate a bit, but pack makers can disable it...

second i changed the output semantics:
from three output itemstacks with fixed recipes to an open system that lets you implement something lie the MagicalCrops dye seeds easily. the node "output" is an object where the keys identify the recipe, and the itemstack is the value. predefined recipes are "chest", "star", "3x3", "2x2" and "default" which can be set globally to another recipe for all shards. Custom recipes can be set numerically so you count the fields line by line and write every set field

for example: ["S S", " S ", "S S"] would be written as "13579".

if you like to pull these changes, i'll upload them, if not i'l just use that jar locally (btw. i have it done for 1.7.10, too, as i still play that mainly)

**Comment by TehNut** [comment]
Note, I am currently rewriting the mod from scratch. It's pretty much done, but I haven't pushed anything, yet.

Why wouldn't you be allowed to PR? Nothing in that thread would suggest otherwise.

> first i added a config value "extraSeedDefaultChance" (float from 0.0 to 1.0, default 0.1) so the seeds will propagate a bit, but pack makers can disable it...

I don't see the point, just modify each seed. Also, I would absolutely never pull that unless the default was `0.0`.

> second i changed the output semantics:
> from three output itemstacks with fixed recipes to an open system that lets you implement something lie the MagicalCrops dye seeds easily. the node "output" is an object where the keys identify the recipe, and the itemstack is the value. predefined recipes are "chest", "star", "3x3", "2x2" and "default" which can be set globally to another recipe for all shards. Custom recipes can be set numerically so you count the fields line by line and write every set field
> 
> for example: ["S S", " S ", "S S"] would be written as "13579".

I'm not a fan of that notation. Just take an array of strings and parse the shape. This would also be a breaking change, so I would only pull this if you kept backwards compat.

> (btw. i have it done for 1.7.10, too, as i still play that mainly)

1.7.10 is dead and I will not be pulling anything for it or releasing new builds.

**Comment by ceiphas** [comment]
i filed a pull request, you can make edits to my branch, if you find some trash ;-)
